# Generated by Django 4.2.1 on 2023-06-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_review_review_rating_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_rating_1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_3',
        ),
    ]
