# Generated by Django 4.2.1 on 2023-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_review_review_rating_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='communication_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='problem_solving_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sociability_bool',
            field=models.BooleanField(default=True),
        ),
    ]
